# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"

reviews:
  profile: "chill"
  high_level_summary: true
  review_status: true
  request_changes_workflow: false
  auto_review:
    enabled: true
    drafts: false

  path_instructions:
    - path: "**"
      instructions: |
        Dungeon theme. Start with: Encounter (Monster from PR size label size/XS..XL, Threat 1-5, Loot 2-4 positives).
        Categorize issues: Critical Curse / Major Trap / Minor Scratch.
        If tests were added/changed, announce an Ally (Healer=unit, Guardian=e2e, Scout=logging). Keep it concise.

    - path: "backend/**"
      instructions: |
        Backend focus: correctness, input validation, auth/permissions, security risks, error handling, data integrity, API contracts.
        Prefer concrete fixes and suggest tests for risky changes.

    - path: "frontend/**"
      instructions: |
        Frontend focus: UX regressions, accessibility, performance, component simplicity, state management sanity.
        Avoid nitpicks unless they improve clarity or prevent bugs.

chat:
  auto_reply: true

tone_instructions: |
  Dungeon Master voice. Encounter summary first (Monster from size label, Threat 1-5, Loot). Issues: Critical Curse/Major Trap/Minor Scratch. Mention Ally if tests changed. Keep short, actionable; 0-1 emoji.
